// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYQquXyj44gnSuY_S-tZgQepLAym6nvg',
    appId: '1:435874197553:web:399d4fb2635a0cdbdb2510',
    messagingSenderId: '435874197553',
    projectId: 'matrimony-app-db266',
    authDomain: 'matrimony-app-db266.firebaseapp.com',
    storageBucket: 'matrimony-app-db266.firebasestorage.app',
    measurementId: 'G-E8GR53RDFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Dyw0y8ESRrE6ySOHx6MKTBDlTaIT-FI',
    appId: '1:435874197553:android:f30eeebd33aaecf8db2510',
    messagingSenderId: '435874197553',
    projectId: 'matrimony-app-db266',
    storageBucket: 'matrimony-app-db266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGR0YBbnkDP5qh0Gatyl_D5hv0jUswuQ',
    appId: '1:435874197553:ios:4cb85d4d2f63d60fdb2510',
    messagingSenderId: '435874197553',
    projectId: 'matrimony-app-db266',
    storageBucket: 'matrimony-app-db266.firebasestorage.app',
    iosBundleId: 'com.example.webkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuGR0YBbnkDP5qh0Gatyl_D5hv0jUswuQ',
    appId: '1:435874197553:ios:4cb85d4d2f63d60fdb2510',
    messagingSenderId: '435874197553',
    projectId: 'matrimony-app-db266',
    storageBucket: 'matrimony-app-db266.firebasestorage.app',
    iosBundleId: 'com.example.webkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpYQquXyj44gnSuY_S-tZgQepLAym6nvg',
    appId: '1:435874197553:web:4ad2992e7e7de369db2510',
    messagingSenderId: '435874197553',
    projectId: 'matrimony-app-db266',
    authDomain: 'matrimony-app-db266.firebaseapp.com',
    storageBucket: 'matrimony-app-db266.firebasestorage.app',
    measurementId: 'G-S79BPSQKRW',
  );
}
